### PR TITLE
Added breadcrumbs

### PR DESCRIPTION
**Pull request by PaLaMuNDeR**
- Added Breadcrumbs data and changed the structure to graph list

### CODE REVIEW

**Comment by vsalvino** [comment]
@PaLaMuNDeR I'm not sure what the purpose of this pull request is... you might want to discuss the feature first to see if we actually want to implement it as part of wagtail-seo, before sinking a ton of time into it. Just a friendly heads-up since I see you are pushing a lot.

**Comment by PaLaMuNDeR** [comment]
@vsalvino I added those features to use them for a project I am working on, so I decided to share them and improve the library. It's up to you which of them you'd like to add, of course :) No hard feelings if you decide otherwise. For the project I am working on right now, it is important to have the Breadcrumbs and the SearchAction functionality, so I decided to contribute.

**Comment by vsalvino** [comment]
Thanks. Can you add a description of what these are / how they will work on the site in the PR? Then I'll review you are done committing.

**Comment by PaLaMuNDeR** [comment]
Sure. Here are the changes:

- Added PotentialAction "SearchAction" 
e.g.
```
"potentialAction": [{
			"@type": "SearchAction",
			"target": "https://example.org/search?&query={query}",
			"query": "required"
		}]
```	

- Added option to add logo and organization image to all pages from Global Settings -> SEO
- PotentialActions now can be added in the Settings -> SEO and applied to the schema of all pages
- Added more SchemaTypes options
- Added script for running the tests 
- Added Breadcrumbs data and changed the structure to graph list 
```
{
	"@context": "http://schema.org",
	"@graph": [{
		"@type": "Type",
		"url": "http://example.org/page/",
		"name": "Page Title",
		"logo": {
			"@type": "ImageObject",
			"URL": "https://imageurl.com"
		},
		"image": ["https://otherimagesurl.com"],
		"potentialAction": [{
			"@type": "SearchAction",
			"target": "https://example.org/search?&query={query}",
			"query": "required"
		}]
	}, {
		"@type": "BreadcrumbList",
		"@id": "http://example.org/page/#breadcrumb",
		"itemListElement": [{
			"@type": "ListItem",
			"position": 1,
			"item": {
				"@type": "WebPage",
				"@id": "http://example.org",
				"url": "http://example.org",
				"name": "Home"
			}
		}, {
			"@type": "ListItem",
			"position": 2,
			"item": {
				"@type": "Type",
				"@id": "http://example.org/page/",
				"url": "http://example.org/page/",
				"name": "Page"
			}
		}]
	}]
}
```

**Comment by vsalvino** [comment]
Hi @PaLaMuNDeR - thanks for all the hard work on this. After doing a bit of review my concern is that this one pull request is packed full of multiple unrelated features (search action, logo, breadcrumbs, etc.)

Can you please split these into individual pull requests so that they can be reviewed independently?

**Comment by PaLaMuNDeR** [comment]
@vsalvino I needed some time, but finally managed to split it into different features

-   Added script for running the tests -> https://github.com/coderedcorp/wagtail-seo/pull/27
-   Added more SchemaTypes options -> https://github.com/coderedcorp/wagtail-seo/pull/31
-   Added Breadcrumbs data and changed the structure to graph list -> https://github.com/coderedcorp/wagtail-seo/pull/28
-   Added PotentialAction "SearchAction" -> https://github.com/coderedcorp/wagtail-seo/pull/29 (please note it is depending on the Graph structure)
-   Added option to add logo and organization image to all pages from Global Settings -> SEO    --> https://github.com/coderedcorp/wagtail-seo/pull/30

**Pull request closed without merging**
