### PR TITLE
Changes required for compatibility with Wagtail 5

### PR DESCRIPTION
**Pull request by cjkpl**
Works on Wagtail 5.0.1 and 5.0.2.

### CODE REVIEW

**Comment by fabienheureux** [comment]
Thanks for this PR @cjkpl  ! 
Do you know is there is any blocker preventing its merge ?

**Comment by cjkpl** [comment]
> Thanks for this PR @cjkpl ! Do you know is there is any blocker preventing its merge ?

Not that I know of.  Until this repo is updated, try using my fork (https://github.com/cjkpl/cjkcms-seo.git) or via pypi: 
```
pip install cjkcms-seo
```
(only pypi package name has been changed, the app is called wagtailseo so it is a drop-in replacement)

I tend to update both SEO and CACHE within days after new Wagtail release, as I use them in my applications.

**Comment by vsalvino** [comment]
Thanks for doing this work! We can't merge this in as-is, because some of the files such as README, setup.py, etc. have changed and point to your fork (cjkcms) instead of wagtail-seo. If you can update this to only include the relevant python code changes, that would be helpful.

Otherwise, I'll make a new PR which includes the relevant changes, once I have some time.

**Comment by vsalvino** [comment]
Closing this in favor of #49 . Thanks everybody for your contributions!

**Pull request closed without merging**
